One of the biggest challenge for a web framework is to offer an efficient and consistent mechanism to handle internal resources such as CSS/JavaScript files, picture files, pdf and so on. Resources can be static (like an icon used across the site) or dynamic (they can be generated on the fly) and they can be made available to users as a download or as a simple URL.

In paragraph 4.6 we have already seen how to add CSS and JavaScript contents to the header section of the page. In the first half of this chapter we will learn a more sophisticated technique that allows us to manage static resources directly from code and “pack” them with our custom components.

Then, in the second part of the chapter we will see how to implement custom resources to enrich our web application with more complex and dynamic functionalities.

=== Static vs dynamic resources
include::_resources/resources_1.adoc[]

=== Resource references
include::_resources/resources_2.adoc[]

=== Package resources
include::_resources/resources_3.adoc[]

=== Adding resources to page header section
include::_resources/resources_4.adoc[]

=== Resource dependencies
include::_resources/resources_5.adoc[]

=== Aggregate multiple resources with resource bundles
include::_resources/resources_6.adoc[]

=== Put JavaScript inside page body
include::_resources/resources_7.adoc[]

=== Header contributors positioning
include::_resources/resources_8.adoc[]

=== Custom resources
include::_resources/resources_9.adoc[]

=== Mounting resources
include::_resources/resources_10.adoc[]

=== Shared resources
include::_resources/resources_11.adoc[]

=== Customizing resource loading
include::_resources/resources_12.adoc[]

=== Summary
include::_resources/resources_13.adoc[]
