Up to now we used component Link to move from a page to another and we have seen that it is quiet similar to a “click” event handler (see paragraph 2.4). 

However this component alone is not enough to build all possible kinds of links we may need in our pages. Therefore, Wicket offers other link components suited for those tasks which can not be accomplished with a basic Link. 

Besides learning new link components, in this chapter we will also see how to customize the page URL generated by Wicket using the encoding facility provided by the framework and the page parameters that can be passed to a target page.

=== PageParameters
include::_urls/urls_1.adoc[]

=== Bookmarkable links
include::_urls/urls_2.adoc[]

=== Automatically creating bookmarkable links with tag wicket:link
include::_urls/urls_3.adoc[]

=== External links
include::_urls/urls_4.adoc[]

=== Stateless links
include::_urls/urls_5.adoc[]

=== Generating structured and clear URLs
include::_urls/urls_6.adoc[]

=== Summary
include::_urls/urls_7.adoc[]
